const groupDetails = [
  {"id": 1, "name": "College Friends", "members": 4},
  {"id": 2, "name": "Work Team", "members": 7},
  {"id": 3, "name": "Gym Buddies", "members": 6},
  {"id": 4, "name": "Book Club", "members": 8},
  {"id": 5, "name": "Family", "members": 12},
  {"id": 6, "name": "Neighborhood Group", "members": 10},
  {"id": 7, "name": "Travel Gang", "members": 5},
  {"id": 8, "name": "Hiking Group", "members": 3},
  {"id": 9, "name": "Photography Club", "members": 9},
  {"id": 10, "name": "Cooking Team", "members": 6},
  {"id": 11, "name": "Music Band", "members": 4},
  {"id": 12, "name": "Tech Enthusiasts", "members": 7},
  {"id": 13, "name": "Movie Buffs", "members": 5},
  {"id": 14, "name": "Art Society", "members": 8},
  {"id": 15, "name": "Gaming Squad", "members": 10},
  {"id": 16, "name": "Study Group", "members": 3},
  {"id": 17, "name": "Volunteer Team", "members": 6},
  {"id": 18, "name": "Running Crew", "members": 4},
  {"id": 19, "name": "Football Fans", "members": 7},
  {"id": 20, "name": "Science Club", "members": 5},
];
