name: Flutter CI/CD

on:
  push:
    branches: [ "main" ] # Trigger only on pushes to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6' # or a specific version like '3.19.0'

      # Get project dependencies
      - name: Install dependencies
        run: flutter pub get

      # Analyze Dart code
      - name: Analyze code
        run: flutter analyze

      # Run tests (optional but recommended)
      - name: Run tests
        run: flutter test

      # Build release APK
      - name: Build release APK
        run: flutter build apk --release

      # Optional: Upload the APK as an artifact
      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
